apiVersion: v1
kind: Pod
metadata:
 name: component-nodejs-analysis-jshint
spec:
 containers:
 - name: jshint
   image: hub.opshub.sh/containerops/analysis-nodejs-jshint:latest
   env:
   - name: CO_DATA
     value: "git_url=https://github.com/jshint/jshint.git path=src"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never