apiVersion: v1
kind: Pod
metadata:
 name: component-nodejs-document-jsdoc
spec:
 containers:
 - name: jsdoc
   image: hub.opshub.sh/containerops/document-nodejs-jsdoc:latest
   env:
   - name: CO_DATA
     value: "git_url=https://github.com/gitgrimbo/jsdoc3-examples.git file=js/Book.js config=conf.json"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never