apiVersion: v1
kind: Pod
metadata:
 name: component-nodejs-analysis-eslint
spec:
 containers:
 - name: eslint
   image: hub.opshub.sh/containerops/analysis-nodejs-eslint:latest
   env:
   - name: CO_DATA
     value: "git_url=https://github.com/spyl94/react-brunch-demo.git path=src format=json"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never