apiVersion: v1
kind: Pod
metadata:
 name: component-nodejs-dependence-yarn
spec:
 containers:
 - name: yarn
   image: hub.opshub.sh/containerops/dependence-nodejs-yarn:latest
   env:
   - name: CO_DATA
     value: "git_url=https://github.com/yangkghjh/try_react.git"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never