apiVersion: v1
kind: Pod
metadata:
 name: component-nodejs-analysis-flow
spec:
 containers:
 - name: flow
   image: hub.opshub.sh/containerops/analysis-nodejs-flow:latest
   env:
   - name: CO_DATA
     value: "git_url=https://github.com/facebook/flow.git"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never