apiVersion: v1
kind: Pod
metadata:
 name: component-nodejs-document-docco
spec:
 containers:
 - name: docco
   image: hub.opshub.sh/containerops/document-nodejs-docco:latest
   env:
   - name: CO_DATA
     value: "git_url=https://github.com/jonpliske/coffeescript_examples.git file=*.coffee"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never