uri: containerops/component/nodejs-component-jscs-test
title: Component for nodejs projects
version: 1
tag: latest
timeout: 0
receivers:
  -
    type: mail
    address: yangkghjh@gmail.com
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: analysis-nodejs-component
    title:  Analysis jscs
    sequencing: sequence
    actions:
      -
        name: component-nodejs-analysis-jscs-action1
        title: action of component-nodejs-analysis-jscs with yaml output and true co-result
        jobs:
          -
            type: component
            kubectl: component-nodejs-analysis-jscs.yaml
            endpoint: hub.opshub.sh/containerops/analysis-nodejs-jscs:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git_url=https://github.com/spyl94/react-brunch-demo.git path=brunch-config.js preset=airbnb"
      -
        name: component-nodejs-analysis-jscs-action2
        title: action of component-nodejs-analysis-jscs with yaml output and false co-result
        jobs:
          -
            type: component
            kubectl: component-nodejs-analysis-jscs.yaml
            endpoint: hub.opshub.sh/containerops/analysis-nodejs-jscs:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git_url=https://github.com/yangkghjh/containerops-nodejs.git path=brunch-config.js preset=airbnb"
  -
    type: end
    name: end
    title: End
